# Generated by Django 5.0.2 on 2024-09-11 16:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_survey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill1', models.IntegerField(default=0)),
                ('skill2', models.IntegerField(default=0)),
                ('skill3', models.IntegerField(default=0)),
                ('skill4', models.IntegerField(default=0)),
                ('skill5', models.IntegerField(default=0)),
                ('skill6', models.IntegerField(default=0)),
                ('skill7', models.IntegerField(default=0)),
                ('skill8', models.IntegerField(default=0)),
                ('skill9', models.IntegerField(default=0)),
                ('skill10', models.IntegerField(default=0)),
                ('choice1', models.CharField(max_length=10)),
                ('choice2', models.CharField(max_length=10)),
                ('choice3', models.CharField(max_length=10)),
                ('choice4', models.CharField(max_length=10)),
                ('choice5', models.CharField(max_length=10)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to=settings.AUTH_USER_MODEL)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='apis.survey')),
            ],
        ),
        migrations.AddConstraint(
            model_name='vote',
            constraint=models.UniqueConstraint(fields=('student', 'survey'), name='unique_student_survey'),
        ),
    ]
