# Generated by Django 5.0.2 on 2024-09-14 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_vote_vote_unique_student_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='untill_at',
        ),
        migrations.AddField(
            model_name='survey',
            name='until_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
